/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AlignContent,
  AlignItems,
  BgAttachment,
  BgBlend,
  BgRepeat,
  BgSize,
  FlexDirection,
  FlexWrap,
  HeightMode,
  Justify,
  OverflowMode,
  ScrollBehavior,
  ScrollSnapType,
  SnapAlign,
  TextAlign,
  TextTransform,
} from './types/common.types';
import {
  ButtonClickDetail,
  ButtonNativeType,
  ButtonSize,
  ButtonTextFamilyToken,
  ButtonTextSizeToken,
  ButtonTextWeightToken,
  ButtonToggleDetail,
  ButtonVariant,
} from './components/button/button.types';
import {
  IndicatorPosition,
  IndicatorType,
  NavigationDisplay,
  NavigationPosition,
  NavigationStyle,
  TintoCarouselSlideChangeDetail,
  TintoCarouselSlideEndDetail,
  TintoCarouselSlideStartDetail,
  TransitionType,
} from './components/carousel/carousel.types';
import {
  AnimationRotate,
  AsKind,
  AspectRatio,
  ImageAnimation,
  ImageFit,
  LinkTarget,
  RepeatValue,
  RoundedPreset,
  TintoImageErrorDetail,
  TintoImageLoadedDetail,
  TintoImagePressDetail,
} from './components/image/image.types';
import {
  Align,
  Color,
  FontFamily,
  FontSize,
  HighlightColor,
  TypingUnit,
  Variant,
} from './components/typography/typography.types';
export {
  AlignContent,
  AlignItems,
  BgAttachment,
  BgBlend,
  BgRepeat,
  BgSize,
  FlexDirection,
  FlexWrap,
  HeightMode,
  Justify,
  OverflowMode,
  ScrollBehavior,
  ScrollSnapType,
  SnapAlign,
  TextAlign,
  TextTransform,
} from './types/common.types';
export {
  ButtonClickDetail,
  ButtonNativeType,
  ButtonSize,
  ButtonTextFamilyToken,
  ButtonTextSizeToken,
  ButtonTextWeightToken,
  ButtonToggleDetail,
  ButtonVariant,
} from './components/button/button.types';
export {
  IndicatorPosition,
  IndicatorType,
  NavigationDisplay,
  NavigationPosition,
  NavigationStyle,
  TintoCarouselSlideChangeDetail,
  TintoCarouselSlideEndDetail,
  TintoCarouselSlideStartDetail,
  TransitionType,
} from './components/carousel/carousel.types';
export {
  AnimationRotate,
  AsKind,
  AspectRatio,
  ImageAnimation,
  ImageFit,
  LinkTarget,
  RepeatValue,
  RoundedPreset,
  TintoImageErrorDetail,
  TintoImageLoadedDetail,
  TintoImagePressDetail,
} from './components/image/image.types';
export {
  Align,
  Color,
  FontFamily,
  FontSize,
  HighlightColor,
  TypingUnit,
  Variant,
} from './components/typography/typography.types';
export namespace Components {
  interface TintoAppRoute {
    /**
     * @default 'stretch'
     */
    align: AlignItems;
    /**
     * @default 'stretch'
     */
    alignContent: AlignContent;
    backdropFilter?: string;
    /**
     * 시각/타이포 토큰
     */
    background?: string;
    /**
     * @default 'scroll'
     */
    bgAttachment: BgAttachment;
    /**
     * @default 'normal'
     */
    bgBlend: BgBlend;
    /**
     * @default '50% 50%'
     */
    bgPosition: string;
    /**
     * @default 'no-repeat'
     */
    bgRepeat: BgRepeat;
    /**
     * @default 'cover'
     */
    bgSize: BgSize;
    border?: string;
    /**
     * @default false
     */
    center: boolean;
    color?: string;
    columnGap?: string;
    /**
     * Flex 레이아웃
     * @default 'column'
     */
    direction: FlexDirection;
    font?: string;
    fontSize?: string;
    fontWeight?: string;
    gap?: string;
    height?: string;
    /**
     * @default 'auto'
     */
    heightMode: HeightMode;
    /**
     * @default 'flex-start'
     */
    justify: Justify;
    letterSpacing?: string;
    lineHeight?: string;
    /**
     * 마진 토큰
     */
    margin?: string;
    marginBlock?: string;
    marginBlockEnd?: string;
    marginBlockStart?: string;
    marginInline?: string;
    marginInlineEnd?: string;
    marginInlineStart?: string;
    maxWidth?: string;
    minHeight?: string;
    overflow?: OverflowMode;
    /**
     * @default 'visible'
     */
    overflowX: OverflowMode;
    /**
     * @default 'visible'
     */
    overflowY: OverflowMode;
    /**
     * 오버레이
     */
    overlay?: string;
    overlayBlend?: string;
    overlayOpacity?: number;
    /**
     * 패딩 토큰
     */
    padding?: string;
    paddingBlock?: string;
    paddingBlockEnd?: string;
    paddingBlockStart?: string;
    paddingInline?: string;
    paddingInlineEnd?: string;
    paddingInlineStart?: string;
    radius?: string;
    rowGap?: string;
    /**
     * 스크롤/세이프에어리어
     * @default false
     */
    safeArea: boolean;
    /**
     * @default 'auto'
     */
    scrollBehavior: ScrollBehavior;
    scrollPadding?: string;
    scrollPaddingBlock?: string;
    scrollPaddingInline?: string;
    scrollSnapType?: ScrollSnapType;
    shadow?: string;
    snapAlign?: SnapAlign;
    /**
     * 배경 이미지
     */
    src?: string;
    textAlign?: TextAlign;
    textTransform?: TextTransform;
    /**
     * 크기/여백
     * @default '100%'
     */
    width: string;
    /**
     * @default 'nowrap'
     */
    wrap: FlexWrap;
  }
  interface TintoButton {
    /**
     * 가로 전체폭 사용 여부
     * @default false
     */
    block: boolean;
    /**
     * 비활성화 여부
     * @default false
     */
    disabled: boolean;
    /**
     * 살짝 떠 있는 느낌의 그림자 사용 여부
     * @default false
     */
    elevated: boolean;
    /**
     * 링크 모드일 때 이동할 href
     */
    href?: string;
    /**
     * 텍스트 라벨(슬롯 대신 사용 가능)
     */
    label?: string;
    /**
     * 로딩 상태 (스피너 표시 + 클릭 막기)
     * @default false
     */
    loading: boolean;
    /**
     * outline 모드 (배경 투명 + border)
     * @default false
     */
    outline: boolean;
    /**
     * pill 형태 (완전 라운드)
     * @default false
     */
    pill: boolean;
    /**
     * 토글 상태 (toggle=true 일 때 사용, mutable)
     * @default false
     */
    pressed: boolean;
    /**
     * border-radius 토큰(숫자만 넣으면 px 처리)
     */
    radius?: string;
    /**
     * 컨테이너 사이즈 토큰 – sm / md / lg
     * @default 'md'
     */
    size: ButtonSize;
    /**
     * 링크 타겟 (href 지정 시)
     */
    target?: '_self' | '_blank' | '_parent' | '_top';
    /**
     * 라벨 폰트 컬러
     */
    textColor?: string;
    /**
     * 라벨 폰트 패밀리 토큰
     */
    textFamily?: ButtonTextFamilyToken | string;
    /**
     * 라벨 폰트 크기 토큰 또는 raw 값 (예: "18px")
     */
    textSize?: ButtonTextSizeToken | string;
    /**
     * 라벨 폰트 두께 토큰 또는 raw 값
     */
    textWeight?: ButtonTextWeightToken | string;
    /**
     * 토글 버튼 모드 (pressed 토글)
     * @default false
     */
    toggle: boolean;
    /**
     * form 동작 타입 - "button": 기본 (아무 것도 안 함) - "submit": 조상 form submit - "reset": 조상 form reset
     * @default 'button'
     */
    type: ButtonNativeType;
    /**
     * 시각 스타일(틀) – primary / secondary / tertiary
     * @default 'primary'
     */
    variant: ButtonVariant;
  }
  /**
   * <tinto-carousel>
   * - 터치/스와이프 슬라이드 지원
   * - 네비게이션 버튼 (옵션)
   * - 인디케이터 (옵션)
   * - 자동 재생 (옵션)
   * - 키보드 네비게이션 지원
   */
  interface TintoCarousel {
    /**
     * 자동 재생
     * @default false
     */
    autoplay: boolean;
    /**
     * 자동 재생 간격 (ms)
     * @default 3000
     */
    autoplayInterval: number;
    /**
     * 현재 슬라이드 인덱스 (0부터 시작)
     * @default 0
     */
    current: number;
    /**
     * 특정 슬라이드로 이동
     */
    goToSlide: (index: number, emitEvent?: boolean) => Promise<void>;
    /**
     * 인디케이터 위치
     * @default 'bottom'
     */
    indicatorPosition: IndicatorPosition;
    /**
     * 인디케이터 타입
     * @default 'dot'
     */
    indicatorType: IndicatorType;
    /**
     * 무한 루프
     * @default false
     */
    loop: boolean;
    /**
     * 네비게이션 버튼 표시 조건
     * @default 'hover'
     */
    navigationDisplay: NavigationDisplay;
    /**
     * 네비게이션 버튼 위치
     * @default 'overlay'
     */
    navigationPosition: NavigationPosition;
    /**
     * 네비게이션 버튼 스타일
     * @default 'circle'
     */
    navigationStyle: NavigationStyle;
    /**
     * 다음 슬라이드
     */
    next: () => Promise<void>;
    /**
     * 이전 슬라이드
     */
    prev: () => Promise<void>;
    /**
     * 인디케이터 표시
     * @default true
     */
    showIndicator: boolean;
    /**
     * 네비게이션 버튼 표시
     * @default true
     */
    showNavigation: boolean;
    /**
     * 슬라이드 개수 (자동 감지 또는 수동 지정)
     */
    slideCount?: number;
    /**
     * 한 번에 표시할 슬라이드 개수
     * @default 1
     */
    slidesPerView: number;
    /**
     * 슬라이드 간격
     * @default '16px'
     */
    spaceBetween: string;
    /**
     * 스와이프 임계값 (px)
     * @default 50
     */
    swipeThreshold: number;
    /**
     * 터치 활성화
     * @default true
     */
    touchEnabled: boolean;
    /**
     * 전환 효과
     * @default 'slide'
     */
    transition: TransitionType;
    /**
     * 전환 시간 (ms)
     * @default 300
     */
    transitionDuration: number;
  }
  /**
   * <tinto-image>
   * - Image/media props + simple animations (spin/float/wobble/pulse)
   * - If placeholder exists, main image loads eagerly by default (fast swap)
   * - rounded="oval" => rounds TOP corners only (bottom corners are square)
   */
  interface TintoImage {
    alt?: string;
    /**
     * @default ''
     */
    animation?: ImageAnimation;
    /**
     * optional scale multiplier applied during animation (esp. spin)
     */
    animationScale?: number;
    /**
     * as="button" support
     */
    as?: AsKind;
    /**
     * auto scale threshold (host width / parent width) for spin
     */
    autoScaleThreshold?: number;
    /**
     * auto scale value applied when threshold exceeded
     */
    autoScaleValue?: number;
    background?: string;
    border?: string;
    crossorigin?: string;
    /**
     * @default 'async'
     */
    decoding?: 'async' | 'sync' | 'auto';
    /**
     * @default false
     */
    disabled?: boolean;
    download?: string;
    /**
     * seconds (e.g., 20)
     * @default 20
     */
    duration?: number;
    /**
     * 에러 발생 시 대체 이미지 URL
     */
    errorFallback?: string;
    /**
     * @default 'cover'
     */
    fit: ImageFit;
    height?: string;
    /**
     * Wrap with anchor when href provided
     */
    href?: string;
    /**
     * Loading policy
     */
    loading?: 'lazy' | 'eager';
    /**
     * pause on hover
     * @default false
     */
    pauseOnHover?: boolean;
    /**
     * Blurred/low-res placeholder URL
     */
    placeholder?: string;
    /**
     * @default true
     */
    play?: boolean;
    /**
     * @default '50% 50%'
     */
    position: string;
    /**
     * Priority: eager + inject <link rel="preload" as="image">
     * @default false
     */
    priority?: boolean;
    /**
     * If radius exists, it overrides rounded preset
     */
    radius?: string;
    /**
     * "w:h", e.g. "16:9", "1:1"
     * @default '16:9'
     */
    ratio: AspectRatio;
    referrerpolicy?: string;
    rel?: string;
    /**
     * 'infinite' or finite count (string/number)
     * @default 'infinite'
     */
    repeat?: RepeatValue;
    /**
     * @default 'right'
     */
    rotate?: AnimationRotate;
    rounded?: RoundedPreset;
    /**
     * Base transform scale (1 = original size)
     */
    scale?: number;
    shadow?: string;
    sizes?: string;
    src?: string;
    /**
     * Responsive images
     */
    srcset?: string;
    /**
     * play/pause on viewport
     * @default false
     */
    startOnViewport?: boolean;
    target?: LinkTarget;
    /**
     * Host box size (CSS inline/block size)
     */
    width?: string;
  }
  interface TintoSection {
    /**
     * @default 'stretch'
     */
    align: AlignItems;
    background?: string;
    /**
     * 가운데 정렬 (maxWidth 사용 시 margin-inline:auto)
     * @default false
     */
    center: boolean;
    color?: string;
    /**
     * Flex 레이아웃 기본값(모바일 우선, 모든 해상도에 동일 적용)
     * @default 'column'
     */
    direction: FlexDirection;
    gap?: string;
    /**
     * 높이 제어 - auto: 내용 높이(기본) - dvh: 동적 뷰포트 기준 최소/정확 높이 - screen: 정확히 100dvh
     * @default 'auto'
     */
    heightMode: HeightMode;
    /**
     * @default 'flex-start'
     */
    justify: Justify;
    margin?: string;
    /**
     * 크기/여백/배경 등 토큰
     */
    maxWidth?: string;
    padding?: string;
    radius?: string;
    /**
     * heightMode가 dvh/screen일 때 내부 스크롤 허용
     * @default false
     */
    scrollable: boolean;
    shadow?: string;
    /**
     * @default 'nowrap'
     */
    wrap: FlexWrap;
  }
  interface TintoTypography {
    /**
     * 정렬
     * @default 'left'
     */
    align: Align;
    /**
     * 시맨틱 태그 강제 (예: variant="h1" + as="h2")
     */
    as?: 'h1' | 'h2' | 'h3' | 'p' | 'span';
    /**
     * 텍스트 색상 (기본 상속)
     * @default 'inherit'
     */
    color: Color;
    /**
     * 폰트 패밀리 preset
     * @default 'system'
     */
    font: FontFamily;
    /**
     * 폰트 크기 토큰 또는 직접 값 (예: "lg", "32px", "2.5rem")
     */
    fontSize?: FontSize | string;
    /**
     * 하이라이트 배경색
     */
    highlight?: HighlightColor;
    /**
     * 하이퍼링크 URL (설정 시 <a>로 감쌈)
     */
    href?: string;
    /**
     * 인라인 여부 (기본 block)
     * @default false
     */
    inline: boolean;
    /**
     * @default false
     */
    pauseOnHover: boolean;
    /**
     * 링크 rel (target이 _blank면 보안 위해 자동 보정됨)
     */
    rel?: string;
    /**
     * 아래 props 들은 기존 롤링용 – API 호환용으로 유지
     * @default 'x'
     */
    rollAxis: 'x' | 'y';
    /**
     * 기본 문장 개수 (슬롯 텍스트를 몇 개로 복제할지, 기본 3개)
     * @default 3
     */
    rollClone: number;
    /**
     * @default '2rem'
     */
    rollGap: string;
    /**
     * @default true
     */
    rollPlay: boolean;
    /**
     * (옵션) 타이핑 duration 토큰 (1~10) – 별도 typingDuration 없으면 fallback
     * @default 5
     */
    rollSpeed: number;
    /**
     * @default false
     */
    rollStartOnViewport: boolean;
    /**
     * rolling=true 이면 타이핑 애니메이션 활성화
     * @default false
     */
    rolling: boolean;
    /**
     * 링크 타겟 (_blank, _self, _parent, _top)
     */
    target?: '_blank' | '_self' | '_parent' | '_top';
    /**
     * 커서( | ) 표시 여부
     * @default true
     */
    typingCursor: boolean;
    /**
     * 개별 문자를 찍는 duration 토큰 (1~10)
     */
    typingDuration?: number;
    /**
     * 삭제 duration 토큰 (1~10, 비우면 typingDuration과 동일)
     */
    typingEraseDuration?: number;
    /**
     * 마지막까지 끝나면 다시 처음부터 반복할지 여부
     * @default true
     */
    typingLoop: boolean;
    /**
     * 타이핑에 사용할 문장 배열. - 문자열 JSON: '["문장1","문장2"]' - 또는 구분자 문자열: '문장1|문장2|문장3' 비워두면 슬롯 텍스트를 rollClone(기본 3)만큼 복제해서 사용.
     */
    typingTexts?: string;
    /**
     * 문자 단위 / 단어 단위
     * @default 'char'
     */
    typingUnit: TypingUnit;
    /**
     * 밑줄 여부
     * @default false
     */
    underline: boolean;
    /**
     * 출력할 HTML 태그 스타일 (시맨틱은 as로 지정 가능)
     * @default 'p'
     */
    variant: Variant;
    /**
     * 텍스트 가시성 (false → hidden)
     * @default true
     */
    visible: boolean;
    /**
     * 두께 (예: 400, 500, 700, 'bold')
     */
    weight?: number | string;
  }
  interface TintoWrapper {
    /**
     * @default 'stretch'
     */
    align: AlignItems;
    alignDesktop?: AlignItems;
    /**
     * 배경(색/그라디언트) + 배경 이미지
     */
    background?: string;
    /**
     * @default 'scroll'
     */
    bgAttachment?: BgAttachment;
    /**
     * @default 'normal'
     */
    bgBlend?: BgBlend;
    /**
     * @default '50% 50%'
     */
    bgPosition?: string;
    /**
     * @default 'no-repeat'
     */
    bgRepeat?: BgRepeat;
    /**
     * @default 'cover'
     */
    bgSize?: BgSize;
    border?: string;
    /**
     * 데스크탑 브레이크포인트 (기본: '1920px')
     * @default '1920px'
     */
    breakpoint: string;
    color?: string;
    /**
     * Flex (모바일 기본)
     * @default 'row'
     */
    direction: FlexDirection;
    /**
     * Flex (데스크탑 오버라이드)
     */
    directionDesktop?: FlexDirection;
    /**
     * 부모를 덮는 모드 (absolute; inset:0)
     * @default false
     */
    fill: boolean;
    gap?: string;
    gapDesktop?: string;
    /**
     * @default 'flex-start'
     */
    justify: Justify;
    justifyDesktop?: Justify;
    margin?: string;
    /**
     * 오버레이
     */
    overlay?: string;
    overlayOpacity?: number;
    /**
     * Box / Visual
     */
    padding?: string;
    radius?: string;
    shadow?: string;
    src?: string;
    /**
     * @default 'nowrap'
     */
    wrap: FlexWrap;
    wrapDesktop?: FlexWrap;
  }
}
export interface TintoButtonCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLTintoButtonElement;
}
export interface TintoCarouselCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLTintoCarouselElement;
}
export interface TintoImageCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLTintoImageElement;
}
declare global {
  interface HTMLTintoAppRouteElement extends Components.TintoAppRoute, HTMLStencilElement {}
  var HTMLTintoAppRouteElement: {
    prototype: HTMLTintoAppRouteElement;
    new (): HTMLTintoAppRouteElement;
  };
  interface HTMLTintoButtonElementEventMap {
    tintoClick: ButtonClickDetail;
    tintoToggle: ButtonToggleDetail;
  }
  interface HTMLTintoButtonElement extends Components.TintoButton, HTMLStencilElement {
    addEventListener<K extends keyof HTMLTintoButtonElementEventMap>(
      type: K,
      listener: (
        this: HTMLTintoButtonElement,
        ev: TintoButtonCustomEvent<HTMLTintoButtonElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLTintoButtonElementEventMap>(
      type: K,
      listener: (
        this: HTMLTintoButtonElement,
        ev: TintoButtonCustomEvent<HTMLTintoButtonElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLTintoButtonElement: {
    prototype: HTMLTintoButtonElement;
    new (): HTMLTintoButtonElement;
  };
  interface HTMLTintoCarouselElementEventMap {
    tintoSlideChange: TintoCarouselSlideChangeDetail;
    tintoSlideStart: TintoCarouselSlideStartDetail;
    tintoSlideEnd: TintoCarouselSlideEndDetail;
  }
  /**
   * <tinto-carousel>
   * - 터치/스와이프 슬라이드 지원
   * - 네비게이션 버튼 (옵션)
   * - 인디케이터 (옵션)
   * - 자동 재생 (옵션)
   * - 키보드 네비게이션 지원
   */
  interface HTMLTintoCarouselElement extends Components.TintoCarousel, HTMLStencilElement {
    addEventListener<K extends keyof HTMLTintoCarouselElementEventMap>(
      type: K,
      listener: (
        this: HTMLTintoCarouselElement,
        ev: TintoCarouselCustomEvent<HTMLTintoCarouselElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLTintoCarouselElementEventMap>(
      type: K,
      listener: (
        this: HTMLTintoCarouselElement,
        ev: TintoCarouselCustomEvent<HTMLTintoCarouselElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLTintoCarouselElement: {
    prototype: HTMLTintoCarouselElement;
    new (): HTMLTintoCarouselElement;
  };
  interface HTMLTintoImageElementEventMap {
    'tinto:loaded': TintoImageLoadedDetail;
    'tinto:error': TintoImageErrorDetail;
    'tinto:press': TintoImagePressDetail;
  }
  /**
   * <tinto-image>
   * - Image/media props + simple animations (spin/float/wobble/pulse)
   * - If placeholder exists, main image loads eagerly by default (fast swap)
   * - rounded="oval" => rounds TOP corners only (bottom corners are square)
   */
  interface HTMLTintoImageElement extends Components.TintoImage, HTMLStencilElement {
    addEventListener<K extends keyof HTMLTintoImageElementEventMap>(
      type: K,
      listener: (
        this: HTMLTintoImageElement,
        ev: TintoImageCustomEvent<HTMLTintoImageElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLTintoImageElementEventMap>(
      type: K,
      listener: (
        this: HTMLTintoImageElement,
        ev: TintoImageCustomEvent<HTMLTintoImageElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLTintoImageElement: {
    prototype: HTMLTintoImageElement;
    new (): HTMLTintoImageElement;
  };
  interface HTMLTintoSectionElement extends Components.TintoSection, HTMLStencilElement {}
  var HTMLTintoSectionElement: {
    prototype: HTMLTintoSectionElement;
    new (): HTMLTintoSectionElement;
  };
  interface HTMLTintoTypographyElement extends Components.TintoTypography, HTMLStencilElement {}
  var HTMLTintoTypographyElement: {
    prototype: HTMLTintoTypographyElement;
    new (): HTMLTintoTypographyElement;
  };
  interface HTMLTintoWrapperElement extends Components.TintoWrapper, HTMLStencilElement {}
  var HTMLTintoWrapperElement: {
    prototype: HTMLTintoWrapperElement;
    new (): HTMLTintoWrapperElement;
  };
  interface HTMLElementTagNameMap {
    'tinto-app-route': HTMLTintoAppRouteElement;
    'tinto-button': HTMLTintoButtonElement;
    'tinto-carousel': HTMLTintoCarouselElement;
    'tinto-image': HTMLTintoImageElement;
    'tinto-section': HTMLTintoSectionElement;
    'tinto-typography': HTMLTintoTypographyElement;
    'tinto-wrapper': HTMLTintoWrapperElement;
  }
}
declare namespace LocalJSX {
  interface TintoAppRoute {
    /**
     * @default 'stretch'
     */
    align?: AlignItems;
    /**
     * @default 'stretch'
     */
    alignContent?: AlignContent;
    backdropFilter?: string;
    /**
     * 시각/타이포 토큰
     */
    background?: string;
    /**
     * @default 'scroll'
     */
    bgAttachment?: BgAttachment;
    /**
     * @default 'normal'
     */
    bgBlend?: BgBlend;
    /**
     * @default '50% 50%'
     */
    bgPosition?: string;
    /**
     * @default 'no-repeat'
     */
    bgRepeat?: BgRepeat;
    /**
     * @default 'cover'
     */
    bgSize?: BgSize;
    border?: string;
    /**
     * @default false
     */
    center?: boolean;
    color?: string;
    columnGap?: string;
    /**
     * Flex 레이아웃
     * @default 'column'
     */
    direction?: FlexDirection;
    font?: string;
    fontSize?: string;
    fontWeight?: string;
    gap?: string;
    height?: string;
    /**
     * @default 'auto'
     */
    heightMode?: HeightMode;
    /**
     * @default 'flex-start'
     */
    justify?: Justify;
    letterSpacing?: string;
    lineHeight?: string;
    /**
     * 마진 토큰
     */
    margin?: string;
    marginBlock?: string;
    marginBlockEnd?: string;
    marginBlockStart?: string;
    marginInline?: string;
    marginInlineEnd?: string;
    marginInlineStart?: string;
    maxWidth?: string;
    minHeight?: string;
    overflow?: OverflowMode;
    /**
     * @default 'visible'
     */
    overflowX?: OverflowMode;
    /**
     * @default 'visible'
     */
    overflowY?: OverflowMode;
    /**
     * 오버레이
     */
    overlay?: string;
    overlayBlend?: string;
    overlayOpacity?: number;
    /**
     * 패딩 토큰
     */
    padding?: string;
    paddingBlock?: string;
    paddingBlockEnd?: string;
    paddingBlockStart?: string;
    paddingInline?: string;
    paddingInlineEnd?: string;
    paddingInlineStart?: string;
    radius?: string;
    rowGap?: string;
    /**
     * 스크롤/세이프에어리어
     * @default false
     */
    safeArea?: boolean;
    /**
     * @default 'auto'
     */
    scrollBehavior?: ScrollBehavior;
    scrollPadding?: string;
    scrollPaddingBlock?: string;
    scrollPaddingInline?: string;
    scrollSnapType?: ScrollSnapType;
    shadow?: string;
    snapAlign?: SnapAlign;
    /**
     * 배경 이미지
     */
    src?: string;
    textAlign?: TextAlign;
    textTransform?: TextTransform;
    /**
     * 크기/여백
     * @default '100%'
     */
    width?: string;
    /**
     * @default 'nowrap'
     */
    wrap?: FlexWrap;
  }
  interface TintoButton {
    /**
     * 가로 전체폭 사용 여부
     * @default false
     */
    block?: boolean;
    /**
     * 비활성화 여부
     * @default false
     */
    disabled?: boolean;
    /**
     * 살짝 떠 있는 느낌의 그림자 사용 여부
     * @default false
     */
    elevated?: boolean;
    /**
     * 링크 모드일 때 이동할 href
     */
    href?: string;
    /**
     * 텍스트 라벨(슬롯 대신 사용 가능)
     */
    label?: string;
    /**
     * 로딩 상태 (스피너 표시 + 클릭 막기)
     * @default false
     */
    loading?: boolean;
    /**
     * 클릭 이벤트 (원본 MouseEvent 전달)
     */
    onTintoClick?: (event: TintoButtonCustomEvent<ButtonClickDetail>) => void;
    /**
     * 토글 상태 변경 이벤트 (pressed 값 전달)
     */
    onTintoToggle?: (event: TintoButtonCustomEvent<ButtonToggleDetail>) => void;
    /**
     * outline 모드 (배경 투명 + border)
     * @default false
     */
    outline?: boolean;
    /**
     * pill 형태 (완전 라운드)
     * @default false
     */
    pill?: boolean;
    /**
     * 토글 상태 (toggle=true 일 때 사용, mutable)
     * @default false
     */
    pressed?: boolean;
    /**
     * border-radius 토큰(숫자만 넣으면 px 처리)
     */
    radius?: string;
    /**
     * 컨테이너 사이즈 토큰 – sm / md / lg
     * @default 'md'
     */
    size?: ButtonSize;
    /**
     * 링크 타겟 (href 지정 시)
     */
    target?: '_self' | '_blank' | '_parent' | '_top';
    /**
     * 라벨 폰트 컬러
     */
    textColor?: string;
    /**
     * 라벨 폰트 패밀리 토큰
     */
    textFamily?: ButtonTextFamilyToken | string;
    /**
     * 라벨 폰트 크기 토큰 또는 raw 값 (예: "18px")
     */
    textSize?: ButtonTextSizeToken | string;
    /**
     * 라벨 폰트 두께 토큰 또는 raw 값
     */
    textWeight?: ButtonTextWeightToken | string;
    /**
     * 토글 버튼 모드 (pressed 토글)
     * @default false
     */
    toggle?: boolean;
    /**
     * form 동작 타입 - "button": 기본 (아무 것도 안 함) - "submit": 조상 form submit - "reset": 조상 form reset
     * @default 'button'
     */
    type?: ButtonNativeType;
    /**
     * 시각 스타일(틀) – primary / secondary / tertiary
     * @default 'primary'
     */
    variant?: ButtonVariant;
  }
  /**
   * <tinto-carousel>
   * - 터치/스와이프 슬라이드 지원
   * - 네비게이션 버튼 (옵션)
   * - 인디케이터 (옵션)
   * - 자동 재생 (옵션)
   * - 키보드 네비게이션 지원
   */
  interface TintoCarousel {
    /**
     * 자동 재생
     * @default false
     */
    autoplay?: boolean;
    /**
     * 자동 재생 간격 (ms)
     * @default 3000
     */
    autoplayInterval?: number;
    /**
     * 현재 슬라이드 인덱스 (0부터 시작)
     * @default 0
     */
    current?: number;
    /**
     * 인디케이터 위치
     * @default 'bottom'
     */
    indicatorPosition?: IndicatorPosition;
    /**
     * 인디케이터 타입
     * @default 'dot'
     */
    indicatorType?: IndicatorType;
    /**
     * 무한 루프
     * @default false
     */
    loop?: boolean;
    /**
     * 네비게이션 버튼 표시 조건
     * @default 'hover'
     */
    navigationDisplay?: NavigationDisplay;
    /**
     * 네비게이션 버튼 위치
     * @default 'overlay'
     */
    navigationPosition?: NavigationPosition;
    /**
     * 네비게이션 버튼 스타일
     * @default 'circle'
     */
    navigationStyle?: NavigationStyle;
    /**
     * 슬라이드 변경 이벤트
     */
    onTintoSlideChange?: (event: TintoCarouselCustomEvent<TintoCarouselSlideChangeDetail>) => void;
    /**
     * 슬라이드 종료 이벤트
     */
    onTintoSlideEnd?: (event: TintoCarouselCustomEvent<TintoCarouselSlideEndDetail>) => void;
    /**
     * 슬라이드 시작 이벤트
     */
    onTintoSlideStart?: (event: TintoCarouselCustomEvent<TintoCarouselSlideStartDetail>) => void;
    /**
     * 인디케이터 표시
     * @default true
     */
    showIndicator?: boolean;
    /**
     * 네비게이션 버튼 표시
     * @default true
     */
    showNavigation?: boolean;
    /**
     * 슬라이드 개수 (자동 감지 또는 수동 지정)
     */
    slideCount?: number;
    /**
     * 한 번에 표시할 슬라이드 개수
     * @default 1
     */
    slidesPerView?: number;
    /**
     * 슬라이드 간격
     * @default '16px'
     */
    spaceBetween?: string;
    /**
     * 스와이프 임계값 (px)
     * @default 50
     */
    swipeThreshold?: number;
    /**
     * 터치 활성화
     * @default true
     */
    touchEnabled?: boolean;
    /**
     * 전환 효과
     * @default 'slide'
     */
    transition?: TransitionType;
    /**
     * 전환 시간 (ms)
     * @default 300
     */
    transitionDuration?: number;
  }
  /**
   * <tinto-image>
   * - Image/media props + simple animations (spin/float/wobble/pulse)
   * - If placeholder exists, main image loads eagerly by default (fast swap)
   * - rounded="oval" => rounds TOP corners only (bottom corners are square)
   */
  interface TintoImage {
    alt?: string;
    /**
     * @default ''
     */
    animation?: ImageAnimation;
    /**
     * optional scale multiplier applied during animation (esp. spin)
     */
    animationScale?: number;
    /**
     * as="button" support
     */
    as?: AsKind;
    /**
     * auto scale threshold (host width / parent width) for spin
     */
    autoScaleThreshold?: number;
    /**
     * auto scale value applied when threshold exceeded
     */
    autoScaleValue?: number;
    background?: string;
    border?: string;
    crossorigin?: string;
    /**
     * @default 'async'
     */
    decoding?: 'async' | 'sync' | 'auto';
    /**
     * @default false
     */
    disabled?: boolean;
    download?: string;
    /**
     * seconds (e.g., 20)
     * @default 20
     */
    duration?: number;
    /**
     * 에러 발생 시 대체 이미지 URL
     */
    errorFallback?: string;
    /**
     * @default 'cover'
     */
    fit?: ImageFit;
    height?: string;
    /**
     * Wrap with anchor when href provided
     */
    href?: string;
    /**
     * Loading policy
     */
    loading?: 'lazy' | 'eager';
    'onTinto:error'?: (event: TintoImageCustomEvent<TintoImageErrorDetail>) => void;
    'onTinto:loaded'?: (event: TintoImageCustomEvent<TintoImageLoadedDetail>) => void;
    'onTinto:press'?: (event: TintoImageCustomEvent<TintoImagePressDetail>) => void;
    /**
     * pause on hover
     * @default false
     */
    pauseOnHover?: boolean;
    /**
     * Blurred/low-res placeholder URL
     */
    placeholder?: string;
    /**
     * @default true
     */
    play?: boolean;
    /**
     * @default '50% 50%'
     */
    position?: string;
    /**
     * Priority: eager + inject <link rel="preload" as="image">
     * @default false
     */
    priority?: boolean;
    /**
     * If radius exists, it overrides rounded preset
     */
    radius?: string;
    /**
     * "w:h", e.g. "16:9", "1:1"
     * @default '16:9'
     */
    ratio?: AspectRatio;
    referrerpolicy?: string;
    rel?: string;
    /**
     * 'infinite' or finite count (string/number)
     * @default 'infinite'
     */
    repeat?: RepeatValue;
    /**
     * @default 'right'
     */
    rotate?: AnimationRotate;
    rounded?: RoundedPreset;
    /**
     * Base transform scale (1 = original size)
     */
    scale?: number;
    shadow?: string;
    sizes?: string;
    src?: string;
    /**
     * Responsive images
     */
    srcset?: string;
    /**
     * play/pause on viewport
     * @default false
     */
    startOnViewport?: boolean;
    target?: LinkTarget;
    /**
     * Host box size (CSS inline/block size)
     */
    width?: string;
  }
  interface TintoSection {
    /**
     * @default 'stretch'
     */
    align?: AlignItems;
    background?: string;
    /**
     * 가운데 정렬 (maxWidth 사용 시 margin-inline:auto)
     * @default false
     */
    center?: boolean;
    color?: string;
    /**
     * Flex 레이아웃 기본값(모바일 우선, 모든 해상도에 동일 적용)
     * @default 'column'
     */
    direction?: FlexDirection;
    gap?: string;
    /**
     * 높이 제어 - auto: 내용 높이(기본) - dvh: 동적 뷰포트 기준 최소/정확 높이 - screen: 정확히 100dvh
     * @default 'auto'
     */
    heightMode?: HeightMode;
    /**
     * @default 'flex-start'
     */
    justify?: Justify;
    margin?: string;
    /**
     * 크기/여백/배경 등 토큰
     */
    maxWidth?: string;
    padding?: string;
    radius?: string;
    /**
     * heightMode가 dvh/screen일 때 내부 스크롤 허용
     * @default false
     */
    scrollable?: boolean;
    shadow?: string;
    /**
     * @default 'nowrap'
     */
    wrap?: FlexWrap;
  }
  interface TintoTypography {
    /**
     * 정렬
     * @default 'left'
     */
    align?: Align;
    /**
     * 시맨틱 태그 강제 (예: variant="h1" + as="h2")
     */
    as?: 'h1' | 'h2' | 'h3' | 'p' | 'span';
    /**
     * 텍스트 색상 (기본 상속)
     * @default 'inherit'
     */
    color?: Color;
    /**
     * 폰트 패밀리 preset
     * @default 'system'
     */
    font?: FontFamily;
    /**
     * 폰트 크기 토큰 또는 직접 값 (예: "lg", "32px", "2.5rem")
     */
    fontSize?: FontSize | string;
    /**
     * 하이라이트 배경색
     */
    highlight?: HighlightColor;
    /**
     * 하이퍼링크 URL (설정 시 <a>로 감쌈)
     */
    href?: string;
    /**
     * 인라인 여부 (기본 block)
     * @default false
     */
    inline?: boolean;
    /**
     * @default false
     */
    pauseOnHover?: boolean;
    /**
     * 링크 rel (target이 _blank면 보안 위해 자동 보정됨)
     */
    rel?: string;
    /**
     * 아래 props 들은 기존 롤링용 – API 호환용으로 유지
     * @default 'x'
     */
    rollAxis?: 'x' | 'y';
    /**
     * 기본 문장 개수 (슬롯 텍스트를 몇 개로 복제할지, 기본 3개)
     * @default 3
     */
    rollClone?: number;
    /**
     * @default '2rem'
     */
    rollGap?: string;
    /**
     * @default true
     */
    rollPlay?: boolean;
    /**
     * (옵션) 타이핑 duration 토큰 (1~10) – 별도 typingDuration 없으면 fallback
     * @default 5
     */
    rollSpeed?: number;
    /**
     * @default false
     */
    rollStartOnViewport?: boolean;
    /**
     * rolling=true 이면 타이핑 애니메이션 활성화
     * @default false
     */
    rolling?: boolean;
    /**
     * 링크 타겟 (_blank, _self, _parent, _top)
     */
    target?: '_blank' | '_self' | '_parent' | '_top';
    /**
     * 커서( | ) 표시 여부
     * @default true
     */
    typingCursor?: boolean;
    /**
     * 개별 문자를 찍는 duration 토큰 (1~10)
     */
    typingDuration?: number;
    /**
     * 삭제 duration 토큰 (1~10, 비우면 typingDuration과 동일)
     */
    typingEraseDuration?: number;
    /**
     * 마지막까지 끝나면 다시 처음부터 반복할지 여부
     * @default true
     */
    typingLoop?: boolean;
    /**
     * 타이핑에 사용할 문장 배열. - 문자열 JSON: '["문장1","문장2"]' - 또는 구분자 문자열: '문장1|문장2|문장3' 비워두면 슬롯 텍스트를 rollClone(기본 3)만큼 복제해서 사용.
     */
    typingTexts?: string;
    /**
     * 문자 단위 / 단어 단위
     * @default 'char'
     */
    typingUnit?: TypingUnit;
    /**
     * 밑줄 여부
     * @default false
     */
    underline?: boolean;
    /**
     * 출력할 HTML 태그 스타일 (시맨틱은 as로 지정 가능)
     * @default 'p'
     */
    variant?: Variant;
    /**
     * 텍스트 가시성 (false → hidden)
     * @default true
     */
    visible?: boolean;
    /**
     * 두께 (예: 400, 500, 700, 'bold')
     */
    weight?: number | string;
  }
  interface TintoWrapper {
    /**
     * @default 'stretch'
     */
    align?: AlignItems;
    alignDesktop?: AlignItems;
    /**
     * 배경(색/그라디언트) + 배경 이미지
     */
    background?: string;
    /**
     * @default 'scroll'
     */
    bgAttachment?: BgAttachment;
    /**
     * @default 'normal'
     */
    bgBlend?: BgBlend;
    /**
     * @default '50% 50%'
     */
    bgPosition?: string;
    /**
     * @default 'no-repeat'
     */
    bgRepeat?: BgRepeat;
    /**
     * @default 'cover'
     */
    bgSize?: BgSize;
    border?: string;
    /**
     * 데스크탑 브레이크포인트 (기본: '1920px')
     * @default '1920px'
     */
    breakpoint?: string;
    color?: string;
    /**
     * Flex (모바일 기본)
     * @default 'row'
     */
    direction?: FlexDirection;
    /**
     * Flex (데스크탑 오버라이드)
     */
    directionDesktop?: FlexDirection;
    /**
     * 부모를 덮는 모드 (absolute; inset:0)
     * @default false
     */
    fill?: boolean;
    gap?: string;
    gapDesktop?: string;
    /**
     * @default 'flex-start'
     */
    justify?: Justify;
    justifyDesktop?: Justify;
    margin?: string;
    /**
     * 오버레이
     */
    overlay?: string;
    overlayOpacity?: number;
    /**
     * Box / Visual
     */
    padding?: string;
    radius?: string;
    shadow?: string;
    src?: string;
    /**
     * @default 'nowrap'
     */
    wrap?: FlexWrap;
    wrapDesktop?: FlexWrap;
  }
  interface IntrinsicElements {
    'tinto-app-route': TintoAppRoute;
    'tinto-button': TintoButton;
    'tinto-carousel': TintoCarousel;
    'tinto-image': TintoImage;
    'tinto-section': TintoSection;
    'tinto-typography': TintoTypography;
    'tinto-wrapper': TintoWrapper;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'tinto-app-route': LocalJSX.TintoAppRoute & JSXBase.HTMLAttributes<HTMLTintoAppRouteElement>;
      'tinto-button': LocalJSX.TintoButton & JSXBase.HTMLAttributes<HTMLTintoButtonElement>;
      /**
       * <tinto-carousel>
       * - 터치/스와이프 슬라이드 지원
       * - 네비게이션 버튼 (옵션)
       * - 인디케이터 (옵션)
       * - 자동 재생 (옵션)
       * - 키보드 네비게이션 지원
       */
      'tinto-carousel': LocalJSX.TintoCarousel & JSXBase.HTMLAttributes<HTMLTintoCarouselElement>;
      /**
       * <tinto-image>
       * - Image/media props + simple animations (spin/float/wobble/pulse)
       * - If placeholder exists, main image loads eagerly by default (fast swap)
       * - rounded="oval" => rounds TOP corners only (bottom corners are square)
       */
      'tinto-image': LocalJSX.TintoImage & JSXBase.HTMLAttributes<HTMLTintoImageElement>;
      'tinto-section': LocalJSX.TintoSection & JSXBase.HTMLAttributes<HTMLTintoSectionElement>;
      'tinto-typography': LocalJSX.TintoTypography &
        JSXBase.HTMLAttributes<HTMLTintoTypographyElement>;
      'tinto-wrapper': LocalJSX.TintoWrapper & JSXBase.HTMLAttributes<HTMLTintoWrapperElement>;
    }
  }
}
